version: '3.8'
services:
  postgres_sba_service:
    container_name: postgres_sba_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./postgresql_volume/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  redis_sba_service:
    container_name: redis_sba_container
    image: 'redis:latest'
    restart: always
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes: 
      - ./redis_volume/:/data