version: '3.8'
services:
  postgres_sba__service:
    container_name: postgres_sba_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./postgresql_volume:/data/db
    ports:
      - 5432:5432
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  postgresql_volume: